# ¿Las ciudades con mayor contaminación presentan tasas más altas de enfermedades respiratorias?

## Exploracion de dataset de urgencias respiratorias

In [2]:
import pandas as pd

In [3]:
urgencias = pd.read_parquet('at_urg_respiratorio_semanal.parquet')

In [4]:
print(f"CANTIDAD DE DATOS:  {urgencias.shape[0] * urgencias.shape[1]}")
print(f"CANTIDAD DE FILAS:  {urgencias.shape[0]}")
print(f"CANTIDAD DE COLUMNAS:  {urgencias.shape[1]}")
print(f"TIPO DE DATO DE CADA COLUMNA:  {urgencias.dtypes}")
print(f"PRIMERAS 5 FILAS:")
display(urgencias.head(5))

CANTIDAD DE DATOS:  85811050
CANTIDAD DE FILAS:  3432442
CANTIDAD DE COLUMNAS:  25
TIPO DE DATO DE CADA COLUMNA:  EstablecimientoCodigo        object
EstablecimientoGlosa         object
RegionCodigo                 object
RegionGlosa                  object
ComunaCodigo                 object
ComunaGlosa                  object
ServicioSaludCodigo          object
ServicioSaludGlosa           object
TipoEstablecimiento          object
DependenciaAdministrativa    object
NivelAtencion                object
TipoUrgencia                 object
Latitud                      object
Longitud                     object
NivelComplejidad             object
Anio                          int32
SemanaEstadistica             int32
OrdenCausa                    int32
Causa                        object
NumTotal                      int32
NumMenor1Anio                 int32
Num1a4Anios                   int32
Num5a14Anios                  int32
Num15a64Anios                 int32
Num65oMas                     int32
dtype: object
PRIMERAS 5 FILAS:

,EstablecimientoCodigo,EstablecimientoGlosa,RegionCodigo,RegionGlosa,ComunaCodigo,ComunaGlosa,ServicioSaludCodigo,ServicioSaludGlosa,TipoEstablecimiento,DependenciaAdministrativa,...,Anio,SemanaEstadistica,OrdenCausa,Causa,NumTotal,NumMenor1Anio,Num1a4Anios,Num5a14Anios,Num15a64Anios,Num65oMas
0,114809,SAPU Pablo de Rokha,13,Región Metropolitana de Santiago,13112,La Pintana,14,Servicio de Salud Metropolitano Sur Oriente,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2021,8,9,Otra causa respiratoria no contenidas en las c...,2,1,1,0,0,0
1,109104,Hospital de Til Til,13,Región Metropolitana de Santiago,13303,Tiltil,9,Servicio de Salud Metropolitano Norte,Hospital,Servicio de Salud,...,2021,26,33,- Causas sistema respiratorio (J00-J98),0,0,0,0,0,0
2,119807,SAPU Alcalde Leocán Portus,8,Región Del Bíobío,8110,Talcahuano,19,Servicio de Salud Talcahuano,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2022,42,10,TOTAL ATENCIONES POR COVID-19 Virus no Identi...,40,7,1,7,22,3
3,105101,Hospital San Pablo (Coquimbo),4,Región De Coquimbo,4102,Coquimbo,5,Servicio de Salud Coquimbo,Hospital,Servicio de Salud,...,2022,5,3,TOTAL CAUSA SISTEMA RESPIRATORIO (J00-J98),67,14,21,21,6,5
4,107828,SAPU Eduardo Frei Montalva,5,Región De Valparaíso,5804,Villa Alemana,7,Servicio de Salud Viña del Mar Quillota,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2024,40,3,TOTAL CAUSA SISTEMA RESPIRATORIO (J00-J98),394,7,37,125,211,14

In [5]:
print(f"DATOS NULOS:  {urgencias.isnull().sum()}")
print("Los datos nulos seran borrados ya que no sirven debido que justo en la columna de nulos estan los datos geograficos")
urgencias = urgencias.dropna()
print(f"DATOS NULOS DESPUES DE BORRAR:  {urgencias.isnull().sum()}")
print(f"CANTIDAD DE DATOS DESPUES DE BORRAR:  {urgencias.shape[0] * urgencias.shape[1]}")

DATOS NULOS:  EstablecimientoCodigo        18576
EstablecimientoGlosa         18576
RegionCodigo                 18576
RegionGlosa                  18576
ComunaCodigo                 18576
ComunaGlosa                  18576
ServicioSaludCodigo          18576
ServicioSaludGlosa           18576
TipoEstablecimiento          18576
DependenciaAdministrativa    18576
NivelAtencion                18576
TipoUrgencia                 18576
Latitud                      18576
Longitud                     18576
NivelComplejidad             18576
Anio                             0
SemanaEstadistica                0
OrdenCausa                       0
Causa                            0
NumTotal                         0
NumMenor1Anio                    0
Num1a4Anios                      0
Num5a14Anios                     0
Num15a64Anios                    0
Num65oMas                        0
dtype: int64
Los datos nulos seran borrados ya que no sirven debido que justo en la columna de nulos estan los datos geograficos
DATOS NULOS DESPUES DE BORRAR:  EstablecimientoCodigo        0
EstablecimientoGlosa         0
RegionCodigo                 0
RegionGlosa                  0
ComunaCodigo                 0
ComunaGlosa                  0
ServicioSaludCodigo          0
ServicioSaludGlosa           0
TipoEstablecimiento          0
DependenciaAdministrativa    0
NivelAtencion                0
TipoUrgencia                 0
Latitud                      0
Longitud                     0
NivelComplejidad             0
Anio                         0
SemanaEstadistica            0
OrdenCausa                   0
Causa                        0
NumTotal                     0
NumMenor1Anio                0
Num1a4Anios                  0
Num5a14Anios                 0
Num15a64Anios                0
Num65oMas                    0
dtype: int64
CANTIDAD DE DATOS DESPUES DE BORRAR:  85346650

In [ ]:
df = urgencias.groupby('ComunaGlosa').size().to_frame('total')

               total
ComunaGlosa
Aisén           6404
Algarrobo       6427
Alhué           6396
Alto Biobío     3252
Alto Hospicio  13240
...              ...
Yumbel          6403
Yungay          6424
Zapallar        4788
Ñiquén          3384
Ñuñoa          12742

[308 rows x 1 columns]

In [10]:
urgencias.head(5)

,EstablecimientoCodigo,EstablecimientoGlosa,RegionCodigo,RegionGlosa,ComunaCodigo,ComunaGlosa,ServicioSaludCodigo,ServicioSaludGlosa,TipoEstablecimiento,DependenciaAdministrativa,...,Anio,SemanaEstadistica,OrdenCausa,Causa,NumTotal,NumMenor1Anio,Num1a4Anios,Num5a14Anios,Num15a64Anios,Num65oMas
0,114809,SAPU Pablo de Rokha,13,Región Metropolitana de Santiago,13112,La Pintana,14,Servicio de Salud Metropolitano Sur Oriente,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2021,8,9,Otra causa respiratoria no contenidas en las c...,2,1,1,0,0,0
1,109104,Hospital de Til Til,13,Región Metropolitana de Santiago,13303,Tiltil,9,Servicio de Salud Metropolitano Norte,Hospital,Servicio de Salud,...,2021,26,33,- Causas sistema respiratorio (J00-J98),0,0,0,0,0,0
2,119807,SAPU Alcalde Leocán Portus,8,Región Del Bíobío,8110,Talcahuano,19,Servicio de Salud Talcahuano,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2022,42,10,TOTAL ATENCIONES POR COVID-19 Virus no Identi...,40,7,1,7,22,3
3,105101,Hospital San Pablo (Coquimbo),4,Región De Coquimbo,4102,Coquimbo,5,Servicio de Salud Coquimbo,Hospital,Servicio de Salud,...,2022,5,3,TOTAL CAUSA SISTEMA RESPIRATORIO (J00-J98),67,14,21,21,6,5
4,107828,SAPU Eduardo Frei Montalva,5,Región De Valparaíso,5804,Villa Alemana,7,Servicio de Salud Viña del Mar Quillota,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2024,40,3,TOTAL CAUSA SISTEMA RESPIRATORIO (J00-J98),394,7,37,125,211,14

In [17]:
df = pd.read_excel('efd-ckan-2023.xlsx')

In [14]:
df

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,220101,100,47.0,NaN,NaN,NaN
1,220101,200,62.0,NaN,NaN,NaN
2,220101,300,59.0,NaN,NaN,NaN
3,220101,400,63.0,NaN,NaN,NaN
4,220101,500,59.0,NaN,NaN,NaN
...,...,...,...,...,...,...
36762,260312,1900,NaN,NaN,NaN,NaN
36763,260312,2000,NaN,NaN,NaN,NaN
36764,260312,2100,NaN,NaN,NaN,NaN
36765,260312,2200,NaN,NaN,NaN,NaN
36766,260312,2300,NaN,NaN,NaN,NaN